version: "3"

services:

  {{cookiecutter.package_name}}:
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    build:
      context: ".."
      dockerfile: "docker/Dockerfile"

    ports: # Used only locally
      - "8080:8080"